apiVersion: v1
kind: Service
metadata:
  annotations:
    tidepool.org/config: |
      ---
      apiVersion: tidepool/v1alpha
      kind:  Mapping
      host: tp
      name: {{ .Release.Namespace -}}-hydrophone-confirm
      prefix: /confirm/
      method: "GET|OPTIONS|POST|PUT|PATCH|DELETE"
      method_regex: true
      rewrite: "/"
      path_redirect: "false"
      service: hydrophone.{{ .Release.Namespace }}:{{ .Values.global.ports.hydrophone }}
  labels:
    app: hydrophone
    helm.sh/chart: {{ include "charts.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: hydrophone
  namespace: {{.Release.Namespace}}
spec:
  ports:
  - name: "http"
    port: {{.Values.global.ports.hydrophone}}
    targetPort: {{.Values.global.ports.hydrophone}}
  selector:
    app: hydrophone
    app.kubernetes.io/name: {{ include "charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
status:
  loadBalancer: {}
