// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "github.com/mdblp/hydrophone/models"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: userId, token
func (_m *UserRepo) GetUser(userId string, token string) (*models.UserData, error) {
	ret := _m.Called(userId, token)

	var r0 *models.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.UserData, error)); ok {
		return rf(userId, token)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.UserData); ok {
		r0 = rf(userId, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserData)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userId, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: userId, user, token
func (_m *UserRepo) UpdateUser(userId string, user models.UserUpdate, token string) error {
	ret := _m.Called(userId, user, token)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, models.UserUpdate, string) error); ok {
		r0 = rf(userId, user, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepo(t mockConstructorTestingTNewUserRepo) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
